openapi: '3.0.0'
info:
  version: 0.0.1
  title: VA Facilities 
  description: |
    
    ## Background

    This API provides information about physical VA facilities. Information available includes
    geographic location, address, phone, hours of operation, and available services. 

    VA operates several different types of facilities, the types represented in this API include:
    - Health facilities
    - Benefits facilities
    - Cemeteries
    - Vet Centers 

    ## Design
    
    ### Authorization
    
    API requests are authorized through a symmetric API token, provided in an HTTP header with name "apikey".

    ### Response Formats
    
    Clients may request several response formats by setting the `Accept` header. 
    - application/json - The default JSON response format complies with JSON API.
    - application/vnd.geo+json - GeoJSON-compliant format, representing each facility as a Feature with a Point geometry.
    - text/csv - Available for the bulk download operation only. Some structured fields are omitted from the CSV response.
          
    ### Response Elements

    Some data elements within the response are only present for facilities of a given type:
    - The patient satisfaction scores contained in the `satisfaction` element are only applicable
      to VA health facilities.
    - The patient wait time values contained in the `wait_times` element are only applicable to 
      VA health facilities.
    - The list of available services in the `services` element is only applicable to VA health and
      benefits facilities.

    ## Reference

    -Raw VA Facilities Open API Spec: http://dev-api.vets.gov/services/va_facilities/docs/v0/api
    -GeoJSON Format: https://tools.ietf.org/html/rfc7946
    -JSON API Format: http://jsonapi.org/format/

  termsOfService: ''
  contact:
    name: developer.va.gov
tags:
  - name: facilities
    description: VA Facilities API
servers: 
  - url: https://dev-api.vets.gov/services/va_facilities/{version}
    description: Vets.gov API development environment
    variables:
      version:
        default: v0
paths:
  /facilities:
    get:
      tags:
        - facilities 
      summary: Query facilities based on a geographic bounding box and optional attribute filters
      operationId: getFacilitiesByLocation
      security:
        - api_key: []
      parameters:
        - in: query
          name: bbox[]
          required: true
          style: form
          exploded: true
          schema:
            type: array
            minItems: 4
            maxItems: 4
            items:
              type: float
        - in: query
          name: type
          required: false
          schema:
            type: string
            enum:
              - health
              - cemetery
              - benefits
              - vet_center
        - in: query
          name: services[]
          style: form
          exploded: true
          schema:
            type: array
            items:
              type: string
      responses:
        '200':
          description: Facilities retrieved successfully
          content:
            application/json:
              schema:
                required:
                  - data
                properties:
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/Facility"
            application/vnd.geo+json:
              schema:
                required:
                  - type
                  - features
                properties:
                  type:
                    type: string
                    enum: ["FeatureCollection"]
                  features:
                    type: array
                    items: 
                      $ref: "#/components/schemas/FacilityFeature"
        '403':
          description: Bad API Token
  /facilities/{id}:
    get:
      tags:
        - facilities 
      summary: Retrieve a specific facility by ID. 
      operationId: getFacilityById
      security:
        - api_key: []
      parameters:
        - in: path
          name: id
          description: |
            Facility ID, in the form `<prefix>_<id>`, where prefix is one of "vha", "vba", "nca", or "vc" 
            for health, benefits, cemetery, or Vet Center facilities respectively. 
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Facility retrieved successfully
          content:
            application/json:
              schema:
                required:
                  - data
                properties:
                  data:
                    $ref: "#/components/schemas/Facility"
            application/vnd.geo+json:
              schema:
                $ref: "#/components/schemas/FacilityFeature"
        '404':
          description: Facility ID not found
        '403':
          description: Bad API Token
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: apikey
      in: header
  schemas:
    Facility:
      description: JSON API-compliant object describing a VA facility
      type: object
      required:
        - id
        - type
        - attributes
      properties:
        id:
          type: string
        type:
          type: string
          enum: ["va_facilities"]
        attributes:
          type: object
          required:
            - name
            - facility_type
            - lat
            - long
          properties:
            name:
              type: string
              example: Washington VA Medical Center
            facility_type:
              type: string
              enum: 
                - va_health_facility
                - va_benefits_facility
                - va_cemetery
                - vet_center
            classification:
              type: string
              example: VA Medical Center (VAMC)
            lat:
              description: Facility latitude
              type: float
              example: 38.9311137
            long:
              description: Facility longitude
              type: float
              example: -77.0109110499999
            website:
              type: string
              format: url
            address:
              type: object
              properties:
                mailing:
                  $ref: "#/components/schemas/Address"
                physical:
                  $ref: "#/components/schemas/Address"
            phone:
              $ref: "#/components/schemas/PhoneNumbers"
            hours:
              $ref: "#/components/schemas/Hours"
            services:
              type: object
              properties:
                other:
                  type: array
                  items:
                    type: string
                    enum: "Online Scheduling"
                health: 
                  type: array
                  items:
                    $ref: "#/components/schemas/HealthService"
                benefits:
                  type: array
                  items:
                    $ref: "#/components/schemas/BenefitsService" 
                last_updated:
                  type: string
                  format: date
            satisfaction:
              type: object
              properties:
                health:
                  $ref: "#/components/schemas/PatientSatisfaction"
                effective_date:
                  type: string
                  format: date
                  example: "2018-01-01"
            wait_times:
              type: object
              properties:
                health:
                  type: array
                  items:
                    $ref: "#/components/schemas/PatientWaitTime"
                effective_date:
                  type: string
                  format: date
                  example: "2018-01-01"
    FacilityFeature:
      description: GeoJSON-complaint Feature object describing a VA Facility
      type: object
      properties:
        type:
          type: string
          enum: ["Feature"]
          example: Feature
        geometry: 
          type: object
          properties:
            type: 
              type: string
              enum: ["Point"]
              example: Point
            coordinates:
              type: array
              minLength: 2
              maxLength: 2
              items:
                type: float
              example: [-77.0367761, 38.9004181] 
        properties:
          type: object
          properties:
            name:
              type: string
              example: Washington VA Medical Center
            id:
              type: string
              example: vha_688
            facility_type:
              type: string
              enum: 
                - va_health_facility
                - va_benefits_facility
                - va_cemetery
                - vet_center
            classification:
              type: string
              example: VA Medical Center (VAMC)
            website:
              type: string
              format: url
            address:
              type: object
              properties:
                mailing:
                  $ref: "#/components/schemas/Address"
                physical:
                  $ref: "#/components/schemas/Address"
            phone:
              $ref: "#/components/schemas/PhoneNumbers"
            hours:
              $ref: "#/components/schemas/Hours"
            services:
              type: object
              properties:
                other:
                  type: array
                  items:
                    type: string
                    enum: "Online Scheduling"
                health: 
                  type: array
                  items:
                    $ref: "#/components/schemas/HealthService"
                benefits:
                  type: array
                  items:
                    $ref: "#/components/schemas/BenefitsService" 
                last_updated:
                  type: string
                  format: date
            satisfaction:
              type: object
              properties:
                health:
                  $ref: "#/components/schemas/PatientSatisfaction"
                effective_date:
                  type: string
                  format: date
                  example: "2018-01-01"
            wait_times:
              type: object
              properties:
                health:
                  type: array
                  items:
                    $ref: "#/components/schemas/PatientWaitTime"
                effective_date:
                  type: string
                  format: date
                  example: "2018-01-01"
    Address:
      type: object
      properties:
        address_1:
          type: string
          example: "50 Irving Street, Northwest"
        address_2:
          type: string
        address_3:
          type: string
        city: 
          type: string
          example: "Washington"
        state: 
          type: string
          example: "DC"
        zip:
          type: string
          example: "20422-0001"
    PhoneNumbers:
      type: object
      properties:
        main: 
          type: string
          example: "202-555-1212"
        fax: 
          type: string
          example: "202-555-1212"
        pharmacy: 
          type: string
          example: "202-555-1212"
        after_hours: 
          type: string
          example: "202-555-1212"
        patient_advocate: 
          type: string
          example: "202-555-1212"
        mental_health_clinic: 
          type: string
          example: "202-555-1212"
        enrollment_coordinator: 
          type: string
          example: "202-555-1212"
    Hours:
      description: |
        Standard hours of operation. Currently formatted as descriptive text suitable for display, with no guarantee of a standard parseable format. Hours of operation may vary due to holidays or other events.
      type: object
      properties:
        Monday:
          type: string
          example: "9AM-5PM"
        Monday:
          type: string
          example: "9AM-5PM"
        Tuesday:
          type: string
          example: "9AM-5PM"
        Wednesday:
          type: string
          example: "9AM-5PM"
        Thursday:
          type: string
          example: "9AM-5PM"
        Friday:
          type: string
          example: "9AM-5PM"
        Saturday:
          type: string
          example: "Closed"
        Sunday:
          type: string
          example: "Closed"
    HealthService:
      type: string
      enum:
        - PrimaryCare 
        - MentalHealthCare 
        - UrgentCare 
        - EmergencyCare 
        - Audiology 
        - Cardiology 
        - Dermatology
        - Gastroenterology 
        - Gynecology 
        - Ophthalmology 
        - Optometry 
        - Orthopedics 
        - Urology 
        - WomensHealth
    BenefitsService:
      type: string
      enum:
        - ApplyingForBenefits 
        - BurialClaimAssistance 
        - DisabilityClaimAssistance
        - eBenefitsRegistrationAssistance 
        - EducationAndCareerCounseling 
        - EducationClaimAssistance
        - FamilyMemberClaimAssistance 
        - HomelessAssistance 
        - InsuranceClaimAssistanceAndFinancialCounseling 
        - IntegratedDisabilityEvaluationSystemAssistance 
        - Pensions
        - PreDischargeClaimAssistance
        - TransitionAssistance
        - UpdatingDirectDepositInformation
        - VAHomeLoanAssistance 
        - VocationalRehabilitationAndEmploymentAssistance 
    PatientSatisfaction:
      description: Veteran-reported satisfaction scores for health care services 
      type: object
      properties:
        primary_care_urgent:
          type: float
          example: 0.85
        primary_care_routine:
          type: float
          example: 0.85
        specialty_care_urgent:
          type: float
          example: 0.85
        specialty_care_routine:
          type: float
          example: 0.85
    PatientWaitTime: 
      description: Expected wait times for new and established patients for a given health care service
      type: object
      properties:
        service:
          $ref: "#components/schemas/HealthService"
        new: 
          description: The average number of days a Veteran who hasn’t been to this location has to wait for a non-urgent appointment
          type: integer
          example: 10
        established:
          description: The average number of days a patient who has already been to this location has to wait for a non-urgent appointment
          type: integer
          example: 5
